name: Offline Tests

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  offline-tests:
    name: Run offline unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run offline tests (unittest)
        run: |
          python -m unittest -v \
            tests.test_datum.DatumTest \
            tests.test_radio.RadioTest.test_pack_method_with_invalid_data_type \
            tests.test_radio.RadioTest.test_unpack_method_with_invalid_packet_size \
            tests.test_radio.RadioTest.test_unpack_method_with_invalid_data_type
